mpbb: clear failcache entries for old port versions
Without this, the number of failcache entries would increase forever,
as only the entry with the current hash is deleted upon success, while
it's usually an older version with a different hash that failed.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -148,6 +148,23 @@ failcache_key() {
     echo "$port $canonical_variants $checksum"
 }
 
+## Delete stale failcache entries for a given port
+#
+# Valid arguments are the first and last parts of a key generated by
+# failcache_key in order, i.e. portname and checksum.
+# Returns 1 if there were no entries for the given port, 0 otherwise.
+failcache_cleanup() {
+    if ! compgen -G "${option_failcache_dir}/${1} *" > /dev/null; then
+        return 1
+    fi
+    for f in "${option_failcache_dir}/${1} "*; do
+        if [ "$(basename "$f" | cut -d ' ' -f3)" != "${2}" ]; then
+            rm -f "${f}"
+        fi
+    done
+    return 0
+}
+
 ## Test whether a given port with variants has previously failed.
 #
 # Valid arguments are a port name, optionally followed by a variant
@@ -159,6 +176,12 @@ failcache_test() {
     if [ $? -ne 0 ]; then
         err "Could not determine failcache key for" "$@"
         return 1
+    fi
+
+    # Delete stale entries first
+    if ! failcache_cleanup $(echo "${key}" | cut -d ' ' -f1) $(echo "${key}" | cut -d ' ' -f3); then
+        # Nothing in the cache for this port, no need to check further
+        return 0
     fi
 
     if [ -f "${option_failcache_dir}/${key}" ]; then
