mp-buildbot: Install dependencies one-by-one
Install dependencies step by step in install-dependencies so that we can track
which dependencies failed and start building a fail cache again. Additionally,
this fixes a problem where
 > port echo depof:wine
would print a list of dependencies but those dependencies were not installed
with the +universal variant as required. To do this, tools/dependencies.tcl
calls mportdepends, which determines the necessary variants of the
dependencies.

git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@151047 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/mpbb-install-dependencies b/mpbb-install-dependencies
--- a/mpbb-install-dependencies
+++ b/mpbb-install-dependencies
@@ -10,19 +10,40 @@ install-dependencies-help() {
 }
 
 install-dependencies() {
+    local dependencies
+
     if [ -z "${option_port}" ]; then
         errmsg "--port is required"
         return 1
     fi
 
-    # skip if the port has no dependencies
-    if [ -z "$(${option_prefix}/bin/port echo depof:${option_port})" ]; then
-        return 0
-    fi
-
-    if ! "${option_prefix}/bin/port" -d install --unrequested depof:"${option_port}"; then
-        echo "Build failed, cleaning up..."
+    # calculate list of dependencies in-order
+    dependencies=$("${option_prefix}/bin/port-tclsh" "${thisdir}/tools/dependencies.tcl" "${option_port}")
+    if [ $? -ne 0 ]; then
+        echo "Calculating dependencies for '${option_port}' failed, cleaning up..." >&2
         cleanup
         return 1
     fi
+
+    if [ -z "$dependencies" ]; then
+        echo "'${option_port}' has no dependencies, continuing..."
+        return 0
+    fi
+
+    echo "Installing dependencies:"
+    echo "$dependencies" | sed -E 's/^/ - /'
+
+    echo "$dependencies" | while read dependency; do
+        # Split portname +variant1+variant2 into portname and variants, where
+        # the variants are optional.
+        depname=${dependency%% *}
+        depvariants=${dependency:${#depname}}
+
+        echo "Installing dependency '${depname}', variants: '${depvariants}'"
+        if ! "${option_prefix}/bin/port" -d install --unrequested "$depname" $depvariants; then
+            echo "Build of dependency '${depname}' failed, cleaning up..." >&2
+            cleanup
+            return 1
+        fi
+    done
 }
