mp-buildbot: cleanup after gather-archives not install-port
git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@150702 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/mpbb-install-port b/mpbb-install-port
--- a/mpbb-install-port
+++ b/mpbb-install-port
@@ -15,9 +15,9 @@ install-port() {
         return 1
     fi
 
-    status=0
-    "${option_prefix}/bin/port" -d install "${option_port}" || status=$?
-
-    cleanup
-    return $status
+    if ! "${option_prefix}/bin/port" -d install "${option_port}"; then
+        echo "Build failed, cleaning up..."
+        cleanup
+        return 1
+    fi
 }
