mpbb: Preserve subcommand return code on exit
git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@152368 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/mpbb b/mpbb
--- a/mpbb
+++ b/mpbb
@@ -186,9 +186,15 @@ done
 if [[ $option_help -eq 1 ]]; then
     usage
 fi
+
 ## Otherwise, run the command and deal with errors
-export PORTSRC="${option_work_dir}/macports.conf"
-if ! $command "$@"; then
-    err "Failed to run $command"
-    exit 1
-fi
+PORTSRC=${option_work_dir}/macports.conf "$command" "$@"
+readonly rc=$?
+case $rc in
+    0)
+        ;;
+    *)
+        err "\`$command' failed to run successfully"
+        ;;
+esac
+exit $rc
