mp-buildbot: Don't re-run previously failed builds
If a port's build has previously failed, we do not want to waste cycles
to re-attempt it (e.g. as dependencies of other ports), unless the
failed port's definition has changed.

To achieve that, create a file with a reference to the last failed build
for every failing port, and fail builds that depend on failed ports
early.

git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@152581 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/mpbb-install-dependencies b/mpbb-install-dependencies
--- a/mpbb-install-dependencies
+++ b/mpbb-install-dependencies
@@ -41,6 +41,9 @@ install-dependencies() {
     local dependencies
     local dependencies_count
     local dependencies_counter
+    local depname
+    local depvariants
+    local failcachecounter
     # $option_log_dir is set in mpbb
     # shellcheck disable=SC2154
     local log_status_dependencies="${option_log_dir}/dependencies-progress.txt"
@@ -53,7 +56,7 @@ install-dependencies() {
     # calculate list of dependencies in-order
     # $option_prefix and $thisdir are set in mpbb
     # shellcheck disable=SC2154
-    dependencies=$("${option_prefix}/bin/port-tclsh" "${thisdir}/tools/dependencies.tcl" "$port")
+    dependencies=$("${option_prefix}/bin/port-tclsh" "${thisdir}/tools/dependencies.tcl" "$@")
     if [ $? -ne 0 ]; then
         echo "Calculating dependencies for '$port' failed, aborting." >&2
         echo "Building '$port' ... [ERROR] (failed to calculate dependencies) maintainers: $(get-maintainers "$port")." >> "$log_subports_progress"
@@ -72,7 +75,31 @@ install-dependencies() {
     echo "$dependencies" | sed -E 's/^/ - /' | tee -a "$log_status_dependencies"
     echo >> "$log_status_dependencies"
 
-    echo "$dependencies" | while read -r dependency; do
+    # Check whether any of the dependencies have previously failed
+    failcachecounter=0
+    while read -r dependency; do
+        # Split portname +variant1+variant2 into portname and variants, where
+        # the variants are optional.
+        depname=${dependency%% *}
+        depvariants=${dependency:${#depname}+1}
+
+        # $depvariants isn't quoted on purpose
+        # shellcheck disable=SC2086
+        if ! failcache_test "$depname" $depvariants; then
+            text="Dependency '${depname}' with variants '${depvariants}' has previously failed and is required."
+            echo "$text" >&2
+            echo "$text" >> "$log_status_dependencies"
+            echo "Building '$port' ... [ERROR] (failed to install dependency '${depname}') maintainers: $(get-maintainers "$port" "${depname}")." >> "$log_subports_progress"
+            failcachecounter=$((failcachecounter + 1))
+        fi
+    done <<<"$dependencies"
+
+    if [ $failcachecounter -gt 0 ]; then
+        echo "Aborting build because $failcachecounter dependencies are known to fail." >&2
+        return 1
+    fi
+
+    while read -r dependency; do
         # Split portname +variant1+variant2 into portname and variants, where
         # the variants are optional.
         depname=${dependency%% *}
@@ -84,14 +111,31 @@ install-dependencies() {
         # $depvariants isn't quoted on purpose
         # shellcheck disable=SC2086
         if ! "${option_prefix}/bin/port" -d install --unrequested "$depname" $depvariants; then
-            echo "Build of dependency '${depname}' failed, aborting." >&2
+            echo "Build of dependency '${depname}' with variants '${depvariants}' failed, aborting." >&2
             echo "[FAIL]" >> "$log_status_dependencies"
             echo "Building '$port' ... [ERROR] (failed to install dependency '${depname}') maintainers: $(get-maintainers "$port" "${depname}")." >> "$log_subports_progress"
+
+            # Update failcache
+            # $depvariants isn't quoted on purpose
+            # shellcheck disable=SC2086
+            failcache_failure "$depname" $depvariants
+            if [ $? -ne 0 ]; then
+                err "failcache_failure $depname $depvariants failed."
+                return 1
+            fi
             return 1
         else
             echo "[OK]" >> "$log_status_dependencies"
+            # Remove failcache if it exists
+            # $depvariants isn't quoted on purpose
+            # shellcheck disable=SC2086
+            failcache_success "$depname" $depvariants
+            if [ $? -ne 0 ]; then
+                err "failcache_success $depname $depvariants failed."
+                return 1
+            fi
             dependencies_counter=$((dependencies_counter + 1))
         fi
-    done
+    done <<<"$dependencies"
 }
 
diff --git a/mpbb-install-port b/mpbb-install-port
--- a/mpbb-install-port
+++ b/mpbb-install-port
@@ -55,10 +55,23 @@ install-port() {
     time_start=$(date +%s)
     # $option_prefix is set in mpbb
     # shellcheck disable=SC2154
-    if ! "${option_prefix}/bin/port" -dk install "$port"; then
+    if "${option_prefix}/bin/port" -dk install "$@"; then
+        # Remove failcache if it exists
+        failcache_success "$@"
+        if [ $? -ne 0 ]; then
+            err "failcache_success" "$@" "failed."
+            return 1
+        fi
+    else
         echo "Build of '$port' failed."
         # log: summary for the portwatcher
         echo "Building '$port' ... [ERROR] maintainers: $(get-maintainers "$port")." >> "$log_subports_progress"
+        # update failcache
+        failcache_failure "$@"
+        if [ $? -ne 0 ]; then
+            err "failcache_failure" "$@" "failed."
+            return 1
+        fi
         return 1
     fi
     time_stop=$(date +%s)
