mpbb: Handle sourcing errors gracefully
There shouldn't actually be any runtime sourcing errors because the
sourced scripts just define functions, and function definitions only
fail due to what we would consider programming errors. But handle them
anyway.

git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@152526 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/mpbb b/mpbb
--- a/mpbb
+++ b/mpbb
@@ -155,16 +155,20 @@ option_log_dir=${option_work_dir}/logs
 # enabled, "${foo[@]}" doesn't work if foo is empty.
 set -- ${args+"${args[@]}"}
 
-# Load the mpbb-$command scripts and source them to load the actual
-# implementations and help messages of available commands.
+# Load the subcommand implementations. Each sourced script "mpbb-FOO"
+# must define functions "FOO" and "FOO-help".
 cmds=()
 thisdir=$(cd "$(dirname "$0")" && pwd)
 for cmdfile in "$thisdir/mpbb-"*; do
     # Unfortunately ShellCheck does not currently support following multiple
     # files, so we'll just disable the warning.
     # shellcheck disable=SC1090
-    . "$cmdfile"
-    cmds+=("${cmdfile#$thisdir/mpbb-}")
+    if . "$cmdfile"; then
+        cmds+=("${cmdfile##*/mpbb-}")
+    else
+        err "failed to load subcommand script \`$cmdfile'"
+        exit 3
+    fi
 done
 
 if (( $# < 1 )); then
