mp-buildbot: create a log file with progress of installed dependencies
git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@151215 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/mpbb-install-dependencies b/mpbb-install-dependencies
--- a/mpbb-install-dependencies
+++ b/mpbb-install-dependencies
@@ -11,11 +11,22 @@ install-dependencies-help() {
 
 install-dependencies() {
     local dependencies
+    local dependencies_count
+    local dependencies_counter
+    local log_status_dependencies
 
     if [ -z "${option_port}" ]; then
         errmsg "--port is required"
         return 1
     fi
+
+    # prepare the log file
+    if ! [[ -d "${option_logdir}" ]] ; then
+        mkdir -p "${option_logdir}"
+    fi
+    log_status_dependencies=${option_logdir}/dependencies-progress.txt
+    # make ure to start with an empty file
+    echo -n "" > $log_status_dependencies
 
     # calculate list of dependencies in-order
     dependencies=$("${option_prefix}/bin/port-tclsh" "${thisdir}/tools/dependencies.tcl" "${option_port}")
@@ -29,8 +40,14 @@ install-dependencies() {
         return 0
     fi
 
-    echo "Installing dependencies:"
+    dependencies_count=$(echo "$dependencies" | wc -l | sed 's/ *//g')
+    dependencies_counter=1
+
+    echo "Installing $dependencies_count dependencies:"
+    echo "Installing $dependencies_count dependencies:" >> $log_status_dependencies
     echo "$dependencies" | sed -E 's/^/ - /'
+    echo "$dependencies" | sed -E 's/^/ - /' >> $log_status_dependencies
+    echo "" >> $log_status_dependencies
 
     echo "$dependencies" | while read dependency; do
         # Split portname +variant1+variant2 into portname and variants, where
@@ -38,10 +55,17 @@ install-dependencies() {
         depname=${dependency%% *}
         depvariants=${dependency:${#depname}+1}
 
-        echo "----> Installing dependency '${depname}', variants: '${depvariants}'"
+        text="Installing dependency ($dependencies_counter of $dependencies_count) '${depname}', variants: '${depvariants}'"
+        echo "----> ${text}"
+        echo -n "${text}' ... " >> $log_status_dependencies
         if ! "${option_prefix}/bin/port" -d install --unrequested "$depname" $depvariants; then
             echo "Build of dependency '${depname}' failed, aborting." >&2
+            echo " [FAIL]" >> $log_status_dependencies
             return 1
+        else
+            echo " [OK]" >> $log_status_dependencies
+            dependencies_counter=$((dependencies_counter + 1))
         fi
     done
 }
+
