mpbb: Search command array for subcommands
Conceptually, the "cmds" array should be the canonical reference for
available subcommands. The sourced scripts are just used to construct
that array.

git-svn-id: https://svn.macports.org/repository/macports/contrib/mp-buildbot@152527 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/mpbb b/mpbb
--- a/mpbb
+++ b/mpbb
@@ -176,9 +176,14 @@ if (( $# < 1 )); then
     usage
 fi
 
-command=$1
+subcmd=$1
 shift
-if [[ ! -f "$thisdir/mpbb-$command" ]]; then
+
+# This loop exits with 0 if cmds contains subcmd or is empty.
+for cmd in "${cmds[@]}"; do
+    [[ $cmd == "$subcmd" ]] && break
+done
+if (( $? != 0 || ${#cmds[@]} == 0 )); then
     err "Unknown command \`$command'"
     usage
 fi
@@ -189,13 +194,13 @@ if [[ $option_help -eq 1 ]]; then
 fi
 
 ## Otherwise, run the command and deal with errors
-PORTSRC=${option_work_dir}/macports.conf "$command" "$@"
+PORTSRC=${option_work_dir}/macports.conf "$subcmd" "$@"
 readonly rc=$?
 case $rc in
     0)
         ;;
     *)
-        err "\`$command' failed to run successfully"
+        err "\`$subcmd' failed to run successfully"
         ;;
 esac
 exit $rc
